"""RaFT-UAV association helpers injected into the upstream
BoT-SORT checkout.

Generated by ``raft_uav.multi_uav_lts.upstream_patch``.  Do not edit this copy;
re-run the patcher after updating RaFT-UAV instead.
"""

from __future__ import annotations

import math
import os

import numpy as np

from tracker import kalman_filter, matching


PATCH_MARKER = "RAFT-UAV LTS PATCH v1"


def env_bool(name, default):
    value = os.environ.get(name)
    if value is None:
        return bool(default)
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ValueError(f"{name} must be a boolean, got {value!r}")


def env_int(name, default, minimum=None):
    value = int(os.environ.get(name, default))
    if minimum is not None and value < minimum:
        raise ValueError(f"{name} must be >= {minimum}, got {value}")
    return value


def env_float(name, default, minimum=None, maximum=None, *, strict_minimum=False):
    value = float(os.environ.get(name, default))
    if not math.isfinite(value):
        raise ValueError(f"{name} must be finite, got {value!r}")
    if minimum is not None:
        invalid = value <= minimum if strict_minimum else value < minimum
        if invalid:
            operator = ">" if strict_minimum else ">="
            raise ValueError(f"{name} must be {operator} {minimum}, got {value}")
    if maximum is not None and value > maximum:
        raise ValueError(f"{name} must be <= {maximum}, got {value}")
    return value


def env_choice(name, default, choices):
    value = os.environ.get(name, default).strip().lower()
    if value not in choices:
        expected = ", ".join(sorted(choices))
        raise ValueError(f"{name} must be one of {expected}, got {value!r}")
    return value


def nwd_distance(tracks, detections, scale):
    """Return normalized Gaussian-Wasserstein box distance in ``[0, 1]``."""

    distance = np.zeros((len(tracks), len(detections)), dtype=float)
    if distance.size == 0:
        return distance

    track_boxes = np.asarray([track.to_xywh() for track in tracks], dtype=float)
    detection_boxes = np.asarray([detection.to_xywh() for detection in detections], dtype=float)
    delta_center = track_boxes[:, None, :2] - detection_boxes[None, :, :2]
    delta_size = track_boxes[:, None, 2:] - detection_boxes[None, :, 2:]
    wasserstein_squared = np.sum(delta_center * delta_center, axis=2)
    wasserstein_squared += 0.25 * np.sum(delta_size * delta_size, axis=2)
    wasserstein = np.sqrt(np.maximum(wasserstein_squared, 0.0))
    distance = 1.0 - np.exp(-wasserstein / scale)
    return np.clip(distance, 0.0, 1.0)


def _motion_gate(kf, tracks, detections):
    valid = np.ones((len(tracks), len(detections)), dtype=bool)
    if valid.size == 0:
        return valid
    measurements = np.asarray([detection.to_xywh() for detection in detections], dtype=float)
    threshold = kalman_filter.chi2inv95[4]
    for row, track in enumerate(tracks):
        gating_distance = kf.gating_distance(
            track.mean,
            track.covariance,
            measurements,
            only_position=False,
            metric="maha",
        )
        valid[row] = np.isfinite(gating_distance) & (gating_distance <= threshold)
    return valid


def association_distance(
    kf,
    tracks,
    detections,
    *,
    with_reid,
    fuse_score,
    proximity_thresh,
    appearance_thresh,
    mode,
    nwd_weight,
    nwd_scale,
    appearance_weight,
    appearance_min_side,
    motion_gate,
):
    """Combine tiny-object geometry, quality-gated appearance, and NIS gating."""

    iou_distance = matching.iou_distance(tracks, detections)
    if iou_distance.size == 0:
        return iou_distance

    scored_iou_distance = (
        matching.fuse_score(iou_distance, detections) if fuse_score else iou_distance.copy()
    )

    if mode == "legacy-min":
        if not with_reid:
            return scored_iou_distance
        embedding_distance = matching.embedding_distance(tracks, detections) / 2.0
        embedding_distance[embedding_distance > appearance_thresh] = 1.0
        embedding_distance[iou_distance > proximity_thresh] = 1.0
        return np.minimum(scored_iou_distance, embedding_distance)

    wasserstein_distance = nwd_distance(tracks, detections, nwd_scale)
    geometry_distance = (
        (1.0 - nwd_weight) * scored_iou_distance
        + nwd_weight * wasserstein_distance
    )

    distance = geometry_distance
    if with_reid:
        try:
            embedding_distance = matching.embedding_distance(tracks, detections) / 2.0
        except (TypeError, ValueError):
            embedding_distance = np.full_like(geometry_distance, np.inf)
        widths_heights = np.asarray([detection.tlwh[2:] for detection in detections], dtype=float)
        min_side = np.min(widths_heights, axis=1)
        quality = np.clip(min_side / appearance_min_side, 0.0, 1.0)
        per_detection_weight = appearance_weight * quality
        reid_geometry_distance = np.minimum(iou_distance, wasserstein_distance)
        valid_appearance = np.isfinite(embedding_distance)
        valid_appearance &= embedding_distance <= appearance_thresh
        valid_appearance &= reid_geometry_distance <= proximity_thresh
        weights = np.broadcast_to(per_detection_weight[None, :], geometry_distance.shape).copy()
        weights[~valid_appearance] = 0.0
        safe_embedding = np.where(valid_appearance, embedding_distance, geometry_distance)
        distance = (1.0 - weights) * geometry_distance + weights * safe_embedding

    distance = np.asarray(distance, dtype=float)
    distance[~np.isfinite(distance)] = 1.0e6
    if motion_gate:
        distance[~_motion_gate(kf, tracks, detections)] = 1.0e6
    return distance
