"""RaFT-UAV association helpers injected into the upstream
BoT-SORT checkout.

Generated by ``raft_uav.multi_uav_lts.upstream_patch``. Do not edit this copy;
re-run the patcher after updating RaFT-UAV instead.
"""

from __future__ import annotations

import math
import os

import numpy as np

from tracker import kalman_filter, matching


PATCH_MARKER = "RAFT-UAV LTS PATCH v1"


def env_bool(name, default):
    value = os.environ.get(name)
    if value is None:
        return bool(default)
    normalized = value.strip().lower()
    if normalized in {"1", "true", "yes", "on"}:
        return True
    if normalized in {"0", "false", "no", "off"}:
        return False
    raise ValueError(f"{name} must be a boolean, got {value!r}")


def env_int(name, default, minimum=None):
    value = int(os.environ.get(name, default))
    if minimum is not None and value < minimum:
        raise ValueError(f"{name} must be >= {minimum}, got {value}")
    return value


def env_float(name, default, minimum=None, maximum=None, *, strict_minimum=False):
    value = float(os.environ.get(name, default))
    if not math.isfinite(value):
        raise ValueError(f"{name} must be finite, got {value!r}")
    if minimum is not None:
        invalid = value <= minimum if strict_minimum else value < minimum
        if invalid:
            operator = ">" if strict_minimum else ">="
            raise ValueError(f"{name} must be {operator} {minimum}, got {value}")
    if maximum is not None and value > maximum:
        raise ValueError(f"{name} must be <= {maximum}, got {value}")
    return value


def env_float_list(name, default, *, minimum=None, maximum=None):
    raw = os.environ.get(name, default)
    values = []
    for item in str(raw).split(","):
        stripped = item.strip()
        if not stripped:
            raise ValueError(f"{name} contains an empty value")
        value = float(stripped)
        if not math.isfinite(value):
            raise ValueError(f"{name} must contain only finite values")
        if minimum is not None and value < minimum:
            raise ValueError(f"{name} values must be >= {minimum}")
        if maximum is not None and value > maximum:
            raise ValueError(f"{name} values must be <= {maximum}")
        values.append(value)
    if not values:
        raise ValueError(f"{name} must contain at least one value")
    if len(set(values)) != len(values):
        raise ValueError(f"{name} must not contain duplicate values")
    return tuple(values)


def env_choice(name, default, choices):
    value = os.environ.get(name, default).strip().lower()
    if value not in choices:
        expected = ", ".join(sorted(choices))
        raise ValueError(f"{name} must be one of {expected}, got {value!r}")
    return value


def nwd_distance(tracks, detections, scale):
    """Return normalized Gaussian-Wasserstein box distance in ``[0, 1]``."""

    distance = np.zeros((len(tracks), len(detections)), dtype=float)
    if distance.size == 0:
        return distance

    track_boxes = np.asarray([track.to_xywh() for track in tracks], dtype=float)
    detection_boxes = np.asarray(
        [detection.to_xywh() for detection in detections], dtype=float
    )
    delta_center = track_boxes[:, None, :2] - detection_boxes[None, :, :2]
    delta_size = track_boxes[:, None, 2:] - detection_boxes[None, :, 2:]
    wasserstein_squared = np.sum(delta_center * delta_center, axis=2)
    wasserstein_squared += 0.25 * np.sum(delta_size * delta_size, axis=2)
    wasserstein = np.sqrt(np.maximum(wasserstein_squared, 0.0))
    distance = 1.0 - np.exp(-wasserstein / scale)
    return np.clip(distance, 0.0, 1.0)


def _expanded_tlbr(detections, scale, image_shape):
    boxes = np.asarray(detections, dtype=float).copy()
    if boxes.size == 0:
        return boxes.reshape(0, 4)
    if boxes.ndim != 2 or boxes.shape[1] < 4:
        raise ValueError("ReID detections must be an N-by-4 array")
    boxes = boxes[:, :4]
    height, width = image_shape[:2]
    if height < 2 or width < 2:
        raise ValueError("ReID image must be at least two pixels in each dimension")

    centers = 0.5 * (boxes[:, :2] + boxes[:, 2:])
    half_sizes = 0.5 * np.maximum(boxes[:, 2:] - boxes[:, :2], 1.0) * scale
    lower = np.floor(centers - half_sizes)
    upper = np.ceil(centers + half_sizes)
    lower[:, 0] = np.clip(lower[:, 0], 0, width - 2)
    lower[:, 1] = np.clip(lower[:, 1], 0, height - 2)
    upper[:, 0] = np.clip(upper[:, 0], lower[:, 0] + 1, width - 1)
    upper[:, 1] = np.clip(upper[:, 1], lower[:, 1] + 1, height - 1)
    return np.concatenate((lower, upper), axis=1)


def _normalize_rows(features):
    array = np.asarray(features, dtype=float)
    if array.ndim != 2:
        raise ValueError("ReID features must be a matrix")
    norms = np.linalg.norm(array, axis=1, keepdims=True)
    valid = np.isfinite(norms[:, 0]) & (norms[:, 0] > 1.0e-12)
    normalized = np.zeros_like(array, dtype=float)
    normalized[valid] = array[valid] / norms[valid]
    return normalized, valid


def multiscale_reid_features(encoder, image, detections, scales):
    """Average normalized ReID embeddings over guarded crop expansions."""

    boxes = np.asarray(detections, dtype=float)
    if boxes.size == 0:
        return []
    scale_values = tuple(float(value) for value in scales)
    if not scale_values:
        raise ValueError("at least one ReID crop scale is required")

    feature_sets = []
    valid_sets = []
    for scale in scale_values:
        if not math.isfinite(scale) or scale <= 0.0:
            raise ValueError("ReID crop scales must be finite and positive")
        scaled_boxes = _expanded_tlbr(boxes, scale, np.shape(image))
        features = np.asarray(encoder.inference(image, scaled_boxes), dtype=float)
        if features.ndim != 2 or features.shape[0] != len(boxes):
            raise ValueError(
                "ReID encoder returned a feature matrix with unexpected shape"
            )
        normalized, valid = _normalize_rows(features)
        feature_sets.append(normalized)
        valid_sets.append(valid)

    stacked = np.stack(feature_sets, axis=0)
    valid_stack = np.stack(valid_sets, axis=0)
    counts = np.sum(valid_stack, axis=0)
    combined = np.sum(stacked, axis=0)
    available = counts > 0
    combined[available] /= counts[available, None]
    combined, normalized_valid = _normalize_rows(combined)
    available &= normalized_valid
    combined[~available] = 0.0
    return combined


def _feature_distance(tracks, detections, attribute):
    distance = np.full((len(tracks), len(detections)), np.inf, dtype=float)
    valid_rows = np.zeros(len(tracks), dtype=bool)
    if distance.size == 0:
        return distance, valid_rows

    detection_features = [
        getattr(detection, "curr_feat", None) for detection in detections
    ]
    detection_valid = np.asarray(
        [feature is not None for feature in detection_features],
        dtype=bool,
    )
    if not np.any(detection_valid):
        return distance, valid_rows

    first_detection = next(
        np.asarray(feature, dtype=float)
        for feature in detection_features
        if feature is not None
    )
    feature_size = first_detection.size
    detections_array = np.zeros((len(detections), feature_size), dtype=float)
    for index, feature in enumerate(detection_features):
        if feature is None:
            continue
        vector = np.asarray(feature, dtype=float).reshape(-1)
        if vector.size != feature_size:
            raise ValueError("inconsistent ReID feature dimensions")
        detections_array[index] = vector
    detections_array, normalized_detection_valid = _normalize_rows(
        detections_array
    )
    detection_valid &= normalized_detection_valid

    tracks_array = np.zeros((len(tracks), feature_size), dtype=float)
    for index, track in enumerate(tracks):
        feature = getattr(track, attribute, None)
        if feature is None:
            continue
        vector = np.asarray(feature, dtype=float).reshape(-1)
        if vector.size != feature_size:
            raise ValueError("inconsistent ReID feature dimensions")
        tracks_array[index] = vector
        valid_rows[index] = True
    tracks_array, normalized_track_valid = _normalize_rows(tracks_array)
    valid_rows &= normalized_track_valid

    cosine = 1.0 - tracks_array @ detections_array.T
    cosine = np.clip(cosine, 0.0, 2.0) / 2.0
    valid_pairs = valid_rows[:, None] & detection_valid[None, :]
    distance[valid_pairs] = cosine[valid_pairs]
    return distance, valid_rows


def _motion_gate(kf, tracks, detections):
    valid = np.ones((len(tracks), len(detections)), dtype=bool)
    if valid.size == 0:
        return valid
    measurements = np.asarray(
        [detection.to_xywh() for detection in detections], dtype=float
    )
    threshold = kalman_filter.chi2inv95[4]
    for row, track in enumerate(tracks):
        gating_distance = kf.gating_distance(
            track.mean,
            track.covariance,
            measurements,
            only_position=False,
            metric="maha",
        )
        valid[row] = np.isfinite(gating_distance) & (gating_distance <= threshold)
    return valid


def _phase_value(early, late, phase):
    late_value = early if late is None else late
    fraction = float(np.clip(phase, 0.0, 1.0))
    return (1.0 - fraction) * early + fraction * late_value


def association_distance(
    kf,
    tracks,
    detections,
    *,
    with_reid,
    fuse_score,
    proximity_thresh,
    appearance_thresh,
    mode,
    nwd_weight,
    nwd_scale,
    appearance_weight,
    appearance_min_side,
    motion_gate,
    anchor_weight=0.0,
    anchor_weight_late=None,
    appearance_weight_late=None,
    appearance_thresh_late=None,
    phase=0.0,
):
    """Combine tiny-object geometry, anchored appearance, and NIS gating."""

    iou_distance = matching.iou_distance(tracks, detections)
    if iou_distance.size == 0:
        return iou_distance

    scored_iou_distance = (
        matching.fuse_score(iou_distance, detections)
        if fuse_score
        else iou_distance.copy()
    )

    if mode == "legacy-min":
        if not with_reid:
            return scored_iou_distance
        embedding_distance = matching.embedding_distance(tracks, detections) / 2.0
        embedding_distance[embedding_distance > appearance_thresh] = 1.0
        embedding_distance[iou_distance > proximity_thresh] = 1.0
        return np.minimum(scored_iou_distance, embedding_distance)

    wasserstein_distance = nwd_distance(tracks, detections, nwd_scale)
    geometry_distance = (
        (1.0 - nwd_weight) * scored_iou_distance
        + nwd_weight * wasserstein_distance
    )

    distance = geometry_distance
    if with_reid:
        rolling_distance, _rolling_rows = _feature_distance(
            tracks,
            detections,
            "smooth_feat",
        )
        anchor_distance, anchor_rows = _feature_distance(
            tracks,
            detections,
            "anchor_feat",
        )
        current_anchor_weight = _phase_value(
            anchor_weight,
            anchor_weight_late,
            phase,
        )
        current_appearance_weight = _phase_value(
            appearance_weight,
            appearance_weight_late,
            phase,
        )
        current_appearance_thresh = _phase_value(
            appearance_thresh,
            appearance_thresh_late,
            phase,
        )

        embedding_distance = rolling_distance.copy()
        anchor_pairs = anchor_rows[:, None] & np.isfinite(anchor_distance)
        both_valid = anchor_pairs & np.isfinite(rolling_distance)
        embedding_distance[both_valid] = (
            (1.0 - current_anchor_weight) * rolling_distance[both_valid]
            + current_anchor_weight * anchor_distance[both_valid]
        )
        anchor_only = anchor_pairs & ~np.isfinite(rolling_distance)
        embedding_distance[anchor_only] = anchor_distance[anchor_only]

        widths_heights = np.asarray(
            [detection.tlwh[2:] for detection in detections],
            dtype=float,
        )
        min_side = np.min(widths_heights, axis=1)
        quality = np.clip(min_side / appearance_min_side, 0.0, 1.0)
        per_detection_weight = current_appearance_weight * quality
        reid_geometry_distance = np.minimum(iou_distance, wasserstein_distance)
        valid_appearance = np.isfinite(embedding_distance)
        valid_appearance &= embedding_distance <= current_appearance_thresh
        valid_appearance &= reid_geometry_distance <= proximity_thresh
        weights = np.broadcast_to(
            per_detection_weight[None, :],
            geometry_distance.shape,
        ).copy()
        weights[~valid_appearance] = 0.0
        safe_embedding = np.where(
            valid_appearance,
            embedding_distance,
            geometry_distance,
        )
        distance = (1.0 - weights) * geometry_distance + weights * safe_embedding

    distance = np.asarray(distance, dtype=float)
    distance[~np.isfinite(distance)] = 1.0e6
    if motion_gate:
        distance[~_motion_gate(kf, tracks, detections)] = 1.0e6
    return distance
