"""Training-example collection for learned radar association likelihoods."""

from __future__ import annotations

from collections.abc import Iterable

import numpy as np
import pandas as pd

from raft_uav.baselines.kalman import AsyncConstantVelocityKalmanTracker, TrackingMeasurement
from raft_uav.baselines.learned_radar_likelihood import radar_association_feature_frame
from raft_uav.baselines.radar_association import (
    _catprob_candidate_pool,
    _events,
    _initial_measurement,
    _nearest_truth_position,
    _nis_scored_candidates,
    _radar_row_to_measurement,
)


def collect_radar_association_training_frame(
    *,
    rf_measurements: Iterable[TrackingMeasurement],
    radar: pd.DataFrame,
    truth: pd.DataFrame,
    flight_name: str | None = None,
    acceleration_std_mps2: float = 4.0,
    radar_xy_std_m: float = 25.0,
    radar_z_std_m: float = 35.0,
    candidate_catprob_threshold: float | None = 0.5,
    positive_gate_m: float = 50.0,
    truth_gate_m: float = 150.0,
    truth_time_gate_s: float = 1.0,
) -> pd.DataFrame:
    """Collect truth-labeled radar candidates from one normalized flight.

    Truth is used only during model training. At each radar frame, the nearest
    candidate to truth is labeled positive if it is within ``positive_gate_m``;
    all remaining candidates in that frame are negative. The online context is
    generated by updating a CV tracker with RF and oracle-positive radar rows.
    """

    if truth.empty or radar.empty:
        return pd.DataFrame()
    if positive_gate_m <= 0.0:
        raise ValueError("positive_gate_m must be positive")
    covariance = np.diag(
        [float(radar_xy_std_m) ** 2, float(radar_xy_std_m) ** 2, float(radar_z_std_m) ** 2]
    )
    events = _events(list(rf_measurements), radar)
    if not events:
        return pd.DataFrame()

    initial_measurement = _initial_measurement(
        events[0],
        association="oracle-nearest-truth",
        covariance=covariance,
        truth=truth,
        truth_gate_m=truth_gate_m,
        truth_time_gate_s=truth_time_gate_s,
    )
    if initial_measurement is None:
        return pd.DataFrame()

    tracker = AsyncConstantVelocityKalmanTracker(
        initial_position=initial_measurement.vector,
        initial_time_s=initial_measurement.time_s,
        acceleration_std_mps2=acceleration_std_mps2,
    )
    rows: list[dict[str, object]] = []
    current_track_id: int | None = None

    for event in events:
        if event["kind"] == "rf":
            measurement = event["measurement"]
            assert isinstance(measurement, TrackingMeasurement)
            tracker.update(measurement)
            continue

        candidates = event["candidates"]
        assert isinstance(candidates, pd.DataFrame)
        time_s = float(event["time_s"])
        tracker.predict_to(time_s)
        candidates = _catprob_candidate_pool(candidates, candidate_catprob_threshold)
        if candidates.empty:
            continue
        scored = _nis_scored_candidates(candidates, tracker, covariance)
        if scored.empty:
            continue

        truth_xyz = _nearest_truth_position(
            truth,
            time_s=time_s,
            max_delta_s=float(truth_time_gate_s),
        )
        if truth_xyz is None:
            continue
        candidate_xyz = scored[["east_m", "north_m", "up_m"]].to_numpy(dtype=float)
        errors = np.linalg.norm(candidate_xyz - truth_xyz.reshape(1, 3), axis=1)
        best_position = int(np.argmin(errors))
        labels = np.zeros(len(scored), dtype=int)
        if float(errors[best_position]) <= float(positive_gate_m):
            labels[best_position] = 1

        feature_frame = radar_association_feature_frame(
            scored,
            tracker_state=tracker.state,
            current_track_id=current_track_id,
        )
        for row_index, (_, candidate) in enumerate(scored.iterrows()):
            row: dict[str, object] = feature_frame.iloc[row_index].to_dict()
            row.update(
                {
                    "label": int(labels[row_index]),
                    "truth_error_m": float(errors[row_index]),
                    "time_s": float(candidate["time_s"]),
                    "frame_index": _optional_int(candidate.get("frame_index")),
                    "track_id": _optional_int(candidate.get("track_id")),
                    "candidate_index": int(row_index),
                    "association_nis": float(candidate.get("association_nis", np.nan)),
                    "flight": flight_name,
                }
            )
            rows.append(row)

        if labels.any():
            selected = scored.iloc[best_position].copy()
            tracker.update(_radar_row_to_measurement(selected, covariance))
            current_track_id = _optional_int(selected.get("track_id"))

    return pd.DataFrame.from_records(rows)


def _optional_int(value: object) -> int | None:
    if value is None:
        return None
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    if not np.isfinite(number):
        return None
    return int(number)
